---
name: CI
on:
  push:
    branches:
      - "main"
  pull_request:
  schedule:
    - cron: "0 4 * * 5"

jobs:
  integration:
    name: integration
    runs-on: macos-latest
    steps:
      - name: Checkout the codebase.
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew install podman
          sudo pip3 install ansible

      - name: Start vagrant
        run: vagrant up

      - name: Configure podman
        run: |
          export CONTAINER_SSHKEY=$PWD/.vagrant/machines/default/virtualbox/private_key
          export CONTAINER_HOST=ssh://vagrant@127.0.0.1:2222/run/user/1000/podman/podman.sock
          podman system connection add vagrant --identity $CONTAINER_SSHKEY $CONTAINER_HOST
      
      - name: Test connectivity
        run: |
          podman info
